[pytest]
addopts = -ra --strict-markers
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
markers =
    unit: teste unitário sem I/O externo
    integration: teste integrado com banco ou API
    contract: teste de contrato e arquitetura
filterwarnings =
    error::DeprecationWarning:app.*
    ignore::DeprecationWarning:passlib.*
    ignore:datetime.datetime.utcnow\(\) is deprecated.*:DeprecationWarning:jose.jwt

norecursedirs = .venv test_backups docs alembic
