"""release growth sprints 121-130
Revision ID: 20260806_0036
Revises: 20260806_0035
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0036'; down_revision='20260806_0035'; branch_labels=None; depends_on=None
TABLES=['release_environments_v2','pilot_programs_v2','mobile_release_profiles','web_releases_v2','learning_paths_v2','documentation_pages_v2','growth_experiments_v2','product_capability_reviews','atlas_roadmaps_v2','release_readiness_assessments']
def j(n): return sa.Column(n,sa.JSON(),nullable=False)
def upgrade():
    op.create_table('release_environments_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('code',sa.String(80),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('base_url',sa.Text(),nullable=False),j('configuration_json'),sa.Column('status',sa.String(30),nullable=False),sa.Column('smoke_tested_at',sa.DateTime(timezone=True)),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('company_id','code',name='uq_release_env_company_code'))
    op.create_table('pilot_programs_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='SET NULL')),sa.Column('pilot_type',sa.String(30),nullable=False),sa.Column('name',sa.String(180),nullable=False),j('objectives_json'),j('metrics_json'),j('findings_json'),sa.Column('status',sa.String(30),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('mobile_release_profiles',sa.Column('id',sa.String(80),primary_key=True),sa.Column('platform',sa.String(20),nullable=False),sa.Column('application_id',sa.String(180),nullable=False),sa.Column('version_name',sa.String(40),nullable=False),sa.Column('build_number',sa.Integer(),nullable=False),sa.Column('signing_configured',sa.Boolean(),nullable=False),sa.Column('privacy_url',sa.Text(),nullable=False),sa.Column('store_status',sa.String(30),nullable=False),sa.Column('rollout_percent',sa.Float(),nullable=False),j('checklist_json'),sa.UniqueConstraint('platform','application_id',name='uq_mobile_platform_app'))
    op.create_table('web_releases_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('version',sa.String(40),nullable=False),sa.Column('target',sa.String(50),nullable=False),j('features_json'),sa.Column('accessibility_score',sa.Float(),nullable=False),sa.Column('performance_score',sa.Float(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('deployed_at',sa.DateTime(timezone=True)))
    op.create_table('learning_paths_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('code',sa.String(100),nullable=False,unique=True),sa.Column('audience',sa.String(80),nullable=False),sa.Column('title',sa.String(180),nullable=False),j('modules_json'),sa.Column('certification_enabled',sa.Boolean(),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False))
    op.create_table('documentation_pages_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('slug',sa.String(180),nullable=False),sa.Column('title',sa.String(220),nullable=False),sa.Column('category',sa.String(80),nullable=False),sa.Column('version',sa.String(40),nullable=False),sa.Column('content_uri',sa.Text(),nullable=False),j('metadata_json'),sa.Column('published',sa.Boolean(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('slug','version',name='uq_doc_slug_version'))
    op.create_table('growth_experiments_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('persona',sa.String(120),nullable=False),sa.Column('hypothesis',sa.Text(),nullable=False),sa.Column('channel',sa.String(80),nullable=False),j('metrics_json'),sa.Column('status',sa.String(30),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('product_capability_reviews',sa.Column('id',sa.String(80),primary_key=True),sa.Column('capability_key',sa.String(160),nullable=False),sa.Column('module',sa.String(100),nullable=False),sa.Column('usage_score',sa.Float(),nullable=False),sa.Column('quality_score',sa.Float(),nullable=False),sa.Column('decision',sa.String(30),nullable=False),sa.Column('notes',sa.Text(),nullable=False),sa.Column('reviewed_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_roadmaps_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('name',sa.String(180),nullable=False),sa.Column('horizon_years',sa.Integer(),nullable=False),sa.Column('vision',sa.Text(),nullable=False),j('pillars_json'),j('milestones_json'),sa.Column('status',sa.String(30),nullable=False),sa.Column('published_at',sa.DateTime(timezone=True)))
    op.create_table('release_readiness_assessments',sa.Column('id',sa.String(80),primary_key=True),sa.Column('release_name',sa.String(120),nullable=False),j('checks_json'),j('blockers_json'),sa.Column('score',sa.Float(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for t in reversed(TABLES): op.drop_table(t)
