"""enterprise operations sprints 81-90"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0032'
down_revision='20260806_0031'
branch_labels=None
depends_on=None

def upgrade():
    tables={
      'consultant_visits':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('consultant_id',sa.String(80),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('scheduled_at',sa.DateTime(timezone=True)),sa.Column('status',sa.String(30)),sa.Column('checklist_json',sa.JSON),sa.Column('findings_json',sa.JSON),sa.Column('action_plan_json',sa.JSON),sa.Column('report_uri',sa.String(700)),sa.Column('signed_at',sa.DateTime(timezone=True))],
      'farm_teams':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('name',sa.String(180)),sa.Column('supervisor_id',sa.String(80),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('members_json',sa.JSON),sa.Column('active',sa.Boolean)],
      'asset_usage_records':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('asset_id',sa.String(80),sa.ForeignKey('farm_assets.id',ondelete='CASCADE')),sa.Column('usage_type',sa.String(50)),sa.Column('meter_value',sa.Float),sa.Column('cost',sa.Float),sa.Column('occurred_at',sa.DateTime(timezone=True)),sa.Column('details_json',sa.JSON)],
      'purchase_requests':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('requester_id',sa.String(80),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('status',sa.String(30)),sa.Column('items_json',sa.JSON),sa.Column('quotations_json',sa.JSON),sa.Column('approved_by',sa.String(80),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('total_amount',sa.Float),sa.Column('created_at',sa.DateTime(timezone=True))],
      'sales_opportunities':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('customer_name',sa.String(180)),sa.Column('stage',sa.String(40)),sa.Column('reserved_entities_json',sa.JSON),sa.Column('amount',sa.Float),sa.Column('margin',sa.Float),sa.Column('contract_uri',sa.String(700)),sa.Column('logistics_json',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True))],
      'crm_leads':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('name',sa.String(180)),sa.Column('source',sa.String(80)),sa.Column('stage',sa.String(40)),sa.Column('contact_json',sa.JSON),sa.Column('estimated_value',sa.Float),sa.Column('next_follow_up_at',sa.DateTime(timezone=True)),sa.Column('converted_company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='SET NULL'))],
      'support_tickets_v2':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('requester_id',sa.String(80),sa.ForeignKey('users.id',ondelete='CASCADE')),sa.Column('title',sa.String(220)),sa.Column('description',sa.Text),sa.Column('priority',sa.String(20)),sa.Column('status',sa.String(30)),sa.Column('sla_due_at',sa.DateTime(timezone=True)),sa.Column('resolution',sa.Text),sa.Column('metadata_json',sa.JSON)],
      'enterprise_workflow_definitions':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('name',sa.String(180)),sa.Column('entity_type',sa.String(80)),sa.Column('steps_json',sa.JSON),sa.Column('conditions_json',sa.JSON),sa.Column('active',sa.Boolean),sa.Column('version',sa.Integer)],
      'enterprise_workflow_instances':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('definition_id',sa.String(80),sa.ForeignKey('enterprise_workflow_definitions.id',ondelete='CASCADE')),sa.Column('entity_id',sa.String(80)),sa.Column('current_step',sa.Integer),sa.Column('status',sa.String(30)),sa.Column('history_json',sa.JSON)],
      'enterprise_documents':[sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('title',sa.String(220)),sa.Column('category',sa.String(80)),sa.Column('storage_uri',sa.String(700)),sa.Column('version',sa.Integer),sa.Column('tags_json',sa.JSON),sa.Column('permissions_json',sa.JSON),sa.Column('expires_at',sa.DateTime(timezone=True)),sa.Column('signed_at',sa.DateTime(timezone=True)),sa.Column('retention_policy',sa.String(80)),sa.Column('created_at',sa.DateTime(timezone=True))],
    }
    for name,cols in tables.items(): op.create_table(name,*cols)

def downgrade():
    for name in ['enterprise_documents','enterprise_workflow_instances','enterprise_workflow_definitions','support_tickets_v2','crm_leads','sales_opportunities','purchase_requests','asset_usage_records','farm_teams','consultant_visits']:
        op.drop_table(name)
