"""saas growth sprints 91-100"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0033'
down_revision='20260806_0032'
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('saas_plans',sa.Column('id',sa.String(80),primary_key=True),sa.Column('code',sa.String(60),nullable=False,unique=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('price_monthly',sa.Float,nullable=False),sa.Column('limits_json',sa.JSON),sa.Column('features_json',sa.JSON),sa.Column('active',sa.Boolean,nullable=False))
    op.create_table('company_subscriptions_v3',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('plan_id',sa.String(80),sa.ForeignKey('saas_plans.id',ondelete='RESTRICT'),nullable=False),sa.Column('status',sa.String(30)),sa.Column('trial_ends_at',sa.DateTime(timezone=True)),sa.Column('current_period_end',sa.DateTime(timezone=True)),sa.Column('cancel_at_period_end',sa.Boolean),sa.Column('provider',sa.String(40)),sa.Column('provider_subscription_id',sa.String(180)))
    op.create_table('billing_invoices_v3',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('subscription_id',sa.String(80),sa.ForeignKey('company_subscriptions_v3.id',ondelete='SET NULL')),sa.Column('number',sa.String(80),unique=True),sa.Column('status',sa.String(30)),sa.Column('amount',sa.Float),sa.Column('discount',sa.Float),sa.Column('tax',sa.Float),sa.Column('currency',sa.String(3)),sa.Column('due_at',sa.DateTime(timezone=True)),sa.Column('paid_at',sa.DateTime(timezone=True)),sa.Column('provider_payload_json',sa.JSON))
    op.create_table('feature_flags_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('key',sa.String(120)),sa.Column('description',sa.Text),sa.Column('enabled',sa.Boolean),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('plan_code',sa.String(60)),sa.Column('rollout_percent',sa.Integer),sa.Column('starts_at',sa.DateTime(timezone=True)),sa.Column('ends_at',sa.DateTime(timezone=True)))
    op.create_table('communication_templates',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('channel',sa.String(30)),sa.Column('code',sa.String(100)),sa.Column('subject',sa.String(220)),sa.Column('body',sa.Text),sa.Column('active',sa.Boolean))
    op.create_table('communication_deliveries',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('template_id',sa.String(80),sa.ForeignKey('communication_templates.id',ondelete='SET NULL')),sa.Column('channel',sa.String(30)),sa.Column('recipient',sa.String(220)),sa.Column('status',sa.String(30)),sa.Column('payload_json',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_table('onboarding_progress',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),unique=True),sa.Column('steps_json',sa.JSON),sa.Column('completion_percent',sa.Float),sa.Column('completed_at',sa.DateTime(timezone=True)))
    op.create_table('data_import_jobs',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('entity_type',sa.String(80)),sa.Column('source_uri',sa.String(700)),sa.Column('mapping_json',sa.JSON),sa.Column('preview_json',sa.JSON),sa.Column('status',sa.String(30)),sa.Column('total_rows',sa.Integer),sa.Column('success_rows',sa.Integer),sa.Column('error_rows',sa.Integer),sa.Column('error_report_json',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_table('data_export_jobs',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80)),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('entity_type',sa.String(80)),sa.Column('format',sa.String(20)),sa.Column('filters_json',sa.JSON),sa.Column('status',sa.String(30)),sa.Column('output_uri',sa.String(700)),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_table('admin_audit_actions',sa.Column('id',sa.String(80),primary_key=True),sa.Column('actor_id',sa.String(80),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('action',sa.String(100)),sa.Column('details_json',sa.JSON),sa.Column('created_at',sa.DateTime(timezone=True)))

def downgrade():
    for name in ['admin_audit_actions','data_export_jobs','data_import_jobs','onboarding_progress','communication_deliveries','communication_templates','feature_flags_v2','billing_invoices_v3','company_subscriptions_v3','saas_plans']:
        op.drop_table(name)
