"""security compliance sprints 111-120
Revision ID: 20260806_0035
Revises: 20260806_0034
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0035'; down_revision='20260806_0034'; branch_labels=None; depends_on=None
TABLES=['security_roles_v2','security_incidents','immutable_audit_records','compliance_privacy_requests','backup_executions_v2','availability_targets','translation_resources','regional_policies','compliance_certifications_v2','continuity_plans_v2']
def j(name,nullable=False): return sa.Column(name,sa.JSON(),nullable=nullable)
def upgrade():
    op.create_table('security_roles_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('code',sa.String(100),nullable=False),sa.Column('name',sa.String(180),nullable=False),j('permissions_json'),j('farm_ids_json'),sa.Column('active',sa.Boolean(),nullable=False),sa.UniqueConstraint('company_id','code',name='uq_security_role_company_code'))
    op.create_table('security_incidents',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('category',sa.String(100),nullable=False),sa.Column('severity',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),j('details_json'),sa.Column('detected_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True)))
    op.create_table('immutable_audit_records',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('actor_id',sa.String(80)),sa.Column('action',sa.String(160),nullable=False),sa.Column('entity_type',sa.String(100),nullable=False),sa.Column('entity_id',sa.String(100),nullable=False),j('before_json'),j('after_json'),sa.Column('previous_hash',sa.String(64),nullable=False),sa.Column('record_hash',sa.String(64),nullable=False,unique=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('compliance_privacy_requests',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('request_type',sa.String(50),nullable=False),sa.Column('subject_reference',sa.String(180),nullable=False),sa.Column('legal_basis',sa.String(180),nullable=False),sa.Column('status',sa.String(30),nullable=False),j('response_json'),sa.Column('due_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('backup_executions_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE')),sa.Column('backup_type',sa.String(40),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('storage_uri',sa.Text(),nullable=False),sa.Column('encrypted',sa.Boolean(),nullable=False),sa.Column('size_bytes',sa.Integer(),nullable=False),sa.Column('checksum',sa.String(128),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('restore_tested_at',sa.DateTime(timezone=True)))
    op.create_table('availability_targets',sa.Column('id',sa.String(80),primary_key=True),sa.Column('service_name',sa.String(120),nullable=False,unique=True),sa.Column('target_percent',sa.Float(),nullable=False),sa.Column('rpo_minutes',sa.Integer(),nullable=False),sa.Column('rto_minutes',sa.Integer(),nullable=False),j('architecture_json'),sa.Column('active',sa.Boolean(),nullable=False))
    op.create_table('translation_resources',sa.Column('id',sa.String(80),primary_key=True),sa.Column('locale',sa.String(20),nullable=False),sa.Column('resource_key',sa.String(240),nullable=False),sa.Column('value',sa.Text(),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.UniqueConstraint('locale','resource_key',name='uq_translation_locale_key'))
    op.create_table('regional_policies',sa.Column('id',sa.String(80),primary_key=True),sa.Column('country_code',sa.String(3),nullable=False),sa.Column('region_code',sa.String(40),nullable=False),sa.Column('policy_type',sa.String(100),nullable=False),j('settings_json'),sa.Column('valid_from',sa.DateTime(timezone=True)),sa.Column('valid_to',sa.DateTime(timezone=True)),sa.Column('active',sa.Boolean(),nullable=False),sa.UniqueConstraint('country_code','region_code','policy_type',name='uq_regional_policy'))
    op.create_table('compliance_certifications_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('certification_type',sa.String(120),nullable=False),sa.Column('issuer',sa.String(180),nullable=False),sa.Column('status',sa.String(30),nullable=False),j('checklist_json'),j('evidence_json'),sa.Column('expires_at',sa.DateTime(timezone=True)))
    op.create_table('continuity_plans_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(180),nullable=False),j('severity_matrix_json'),j('contacts_json'),j('runbooks_json'),sa.Column('status',sa.String(30),nullable=False),sa.Column('last_exercised_at',sa.DateTime(timezone=True)),sa.Column('next_review_at',sa.DateTime(timezone=True)))
def downgrade():
    for table in reversed(TABLES): op.drop_table(table)
