"""Blocos 1 a 5: IA, geo, pastagens, agricultura e genética.
Revision ID: 20260806_0023
Revises: 20260806_0022
"""
from alembic import op
import sqlalchemy as sa
revision="20260806_0023"; down_revision="20260806_0022"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("atlas_geo_assets",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("asset_type",sa.String(50),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("geometry_type",sa.String(30),nullable=False,server_default="Point"),sa.Column("geometry_json",sa.JSON(),nullable=False),sa.Column("properties_json",sa.JSON(),nullable=False),sa.Column("source",sa.String(60),nullable=False,server_default="manual"),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_geo_assets_company_farm_type","atlas_geo_assets",["company_id","farm_id","asset_type"])
    op.create_table("atlas_pasture_records",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("paddock_id",sa.String(80),sa.ForeignKey("atlas_geo_assets.id",ondelete="SET NULL"),nullable=True),sa.Column("record_type",sa.String(50),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("grass_species",sa.String(120),nullable=False,server_default=""),sa.Column("area_ha",sa.Float(),nullable=False,server_default="0"),sa.Column("height_cm",sa.Float(),nullable=False,server_default="0"),sa.Column("forage_mass_kg_dm_ha",sa.Float(),nullable=False,server_default="0"),sa.Column("utilization_percent",sa.Float(),nullable=False,server_default="50"),sa.Column("stocking_au",sa.Float(),nullable=False,server_default="0"),sa.Column("days_available",sa.Float(),nullable=False,server_default="0"),sa.Column("input_name",sa.String(160),nullable=False,server_default=""),sa.Column("input_quantity",sa.Float(),nullable=False,server_default="0"),sa.Column("input_unit",sa.String(40),nullable=False,server_default=""),sa.Column("cost",sa.Float(),nullable=False,server_default="0"),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_pasture_farm_paddock_date","atlas_pasture_records",["farm_id","paddock_id","observed_at"])
    op.create_table("atlas_agriculture_records",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("field_id",sa.String(80),sa.ForeignKey("atlas_geo_assets.id",ondelete="SET NULL"),nullable=True),sa.Column("record_type",sa.String(50),nullable=False),sa.Column("crop_name",sa.String(120),nullable=False,server_default=""),sa.Column("cultivar",sa.String(120),nullable=False,server_default=""),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("area_ha",sa.Float(),nullable=False,server_default="0"),sa.Column("quantity",sa.Float(),nullable=False,server_default="0"),sa.Column("unit",sa.String(40),nullable=False,server_default=""),sa.Column("unit_cost",sa.Float(),nullable=False,server_default="0"),sa.Column("destination",sa.String(120),nullable=False,server_default=""),sa.Column("linked_nutrition_plan_id",sa.String(80),nullable=True),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_agriculture_farm_crop_date","atlas_agriculture_records",["farm_id","crop_name","occurred_at"])
    op.create_table("atlas_genetic_profiles",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("animal_id",sa.String(80),sa.ForeignKey("livestock_animals.id",ondelete="CASCADE"),nullable=False),sa.Column("sire_animal_id",sa.String(80),sa.ForeignKey("livestock_animals.id",ondelete="SET NULL"),nullable=True),sa.Column("dam_animal_id",sa.String(80),sa.ForeignKey("livestock_animals.id",ondelete="SET NULL"),nullable=True),sa.Column("registry_number",sa.String(120),nullable=False,server_default=""),sa.Column("breed_composition_json",sa.JSON(),nullable=False),sa.Column("dep_json",sa.JSON(),nullable=False),sa.Column("economic_index",sa.Float(),nullable=False,server_default="0"),sa.Column("genetic_score",sa.Float(),nullable=False,server_default="0"),sa.Column("inbreeding_coefficient",sa.Float(),nullable=False,server_default="0"),sa.Column("dna_verified",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("source",sa.String(80),nullable=False,server_default="manual"),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_genetics_company_animal","atlas_genetic_profiles",["company_id","animal_id"],unique=True)
    op.create_table("atlas_ai_forecasts",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("animal_id",sa.String(80),sa.ForeignKey("livestock_animals.id",ondelete="SET NULL"),nullable=True),sa.Column("lot_id",sa.String(80),sa.ForeignKey("herd_lots.id",ondelete="SET NULL"),nullable=True),sa.Column("forecast_type",sa.String(60),nullable=False),sa.Column("horizon_days",sa.Integer(),nullable=False,server_default="30"),sa.Column("score",sa.Float(),nullable=False,server_default="0"),sa.Column("confidence_percent",sa.Float(),nullable=False,server_default="0"),sa.Column("prediction_json",sa.JSON(),nullable=False),sa.Column("evidence_json",sa.JSON(),nullable=False),sa.Column("recommendation",sa.Text(),nullable=False,server_default=""),sa.Column("model_version",sa.String(60),nullable=False,server_default="rules-v1"),sa.Column("generated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_ai_forecast_farm_type","atlas_ai_forecasts",["farm_id","forecast_type","generated_at"])

def downgrade():
    for t in ["atlas_ai_forecasts","atlas_genetic_profiles","atlas_agriculture_records","atlas_pasture_records","atlas_geo_assets"]: op.drop_table(t)
