"""Atlas blocks 6 to 10: commercial, consulting, enterprise, BI and product.

Revision ID: 20260806_0024
Revises: 20260806_0023
"""
from alembic import op
import sqlalchemy as sa

revision = "20260806_0024"
down_revision = "20260806_0023"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("atlas_business_parties", sa.Column("id",sa.String(80),primary_key=True), sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False), sa.Column("tenant_id",sa.String(80),nullable=False), sa.Column("party_type",sa.String(30),nullable=False), sa.Column("name",sa.String(180),nullable=False), sa.Column("document",sa.String(40),nullable=False,server_default=""), sa.Column("email",sa.String(180),nullable=False,server_default=""), sa.Column("phone",sa.String(40),nullable=False,server_default=""), sa.Column("address_json",sa.JSON(),nullable=False,server_default=sa.text("'{}'")), sa.Column("crm_stage",sa.String(40),nullable=False,server_default="active"), sa.Column("notes",sa.Text(),nullable=False,server_default=""), sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()), sa.Column("created_at",sa.DateTime(timezone=True),nullable=False), sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_atlas_party_company_type_name","atlas_business_parties",["company_id","party_type","name"])
    op.create_table("atlas_commercial_documents", sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="SET NULL")),sa.Column("party_id",sa.String(80),sa.ForeignKey("atlas_business_parties.id",ondelete="SET NULL")),sa.Column("document_type",sa.String(40),nullable=False),sa.Column("number",sa.String(80),nullable=False,server_default=""),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("total_amount",sa.Float(),nullable=False,server_default="0"),sa.Column("currency",sa.String(10),nullable=False,server_default="BRL"),sa.Column("items_json",sa.JSON(),nullable=False),sa.Column("logistics_json",sa.JSON(),nullable=False),sa.Column("fiscal_json",sa.JSON(),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("notes",sa.Text(),nullable=False,server_default=""),sa.Column("created_by",sa.String(80),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("atlas_consulting_visits",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("consultant_user_id",sa.String(80),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("title",sa.String(180),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("checklist_json",sa.JSON(),nullable=False),sa.Column("photos_json",sa.JSON(),nullable=False),sa.Column("findings_json",sa.JSON(),nullable=False),sa.Column("report_text",sa.Text(),nullable=False,server_default=""),sa.Column("opinion_text",sa.Text(),nullable=False,server_default=""),sa.Column("signature_json",sa.JSON(),nullable=False),sa.Column("previous_visit_id",sa.String(80),sa.ForeignKey("atlas_consulting_visits.id",ondelete="SET NULL")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("atlas_action_plan_items",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="CASCADE"),nullable=False),sa.Column("visit_id",sa.String(80),sa.ForeignKey("atlas_consulting_visits.id",ondelete="SET NULL")),sa.Column("title",sa.String(180),nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("area",sa.String(50),nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("assigned_user_id",sa.String(80),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("due_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("follow_up_at",sa.DateTime(timezone=True)),sa.Column("expected_result",sa.Text(),nullable=False),sa.Column("actual_result",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("atlas_workflow_definitions",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("code",sa.String(80),nullable=False),sa.Column("name",sa.String(180),nullable=False),sa.Column("entity_type",sa.String(60),nullable=False),sa.Column("steps_json",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","code",name="uq_atlas_workflow_company_code"))
    op.create_table("atlas_workflow_instances",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("workflow_id",sa.String(80),sa.ForeignKey("atlas_workflow_definitions.id",ondelete="CASCADE"),nullable=False),sa.Column("entity_type",sa.String(60),nullable=False),sa.Column("entity_id",sa.String(80),nullable=False),sa.Column("current_step",sa.Integer(),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("history_json",sa.JSON(),nullable=False),sa.Column("started_by",sa.String(80),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)))
    op.create_table("atlas_api_credentials",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("key_prefix",sa.String(24),nullable=False),sa.Column("key_hash",sa.String(160),nullable=False),sa.Column("scopes_json",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("last_used_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("company_id","key_prefix",name="uq_atlas_api_key_company_prefix"))
    op.create_table("atlas_webhook_endpoints",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("name",sa.String(120),nullable=False),sa.Column("url",sa.String(500),nullable=False),sa.Column("events_json",sa.JSON(),nullable=False),sa.Column("secret_hash",sa.String(160),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("last_delivery_at",sa.DateTime(timezone=True)),sa.Column("last_status_code",sa.Integer()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("atlas_subscriptions",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("plan_code",sa.String(50),nullable=False),sa.Column("status",sa.String(30),nullable=False),sa.Column("billing_cycle",sa.String(20),nullable=False),sa.Column("amount",sa.Float(),nullable=False),sa.Column("provider",sa.String(40),nullable=False),sa.Column("provider_customer_id",sa.String(160),nullable=False),sa.Column("provider_subscription_id",sa.String(160),nullable=False),sa.Column("trial_ends_at",sa.DateTime(timezone=True)),sa.Column("current_period_ends_at",sa.DateTime(timezone=True)),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("atlas_analytics_snapshots",sa.Column("id",sa.String(80),primary_key=True),sa.Column("company_id",sa.String(80),sa.ForeignKey("companies.id",ondelete="CASCADE"),nullable=False),sa.Column("tenant_id",sa.String(80),nullable=False),sa.Column("farm_id",sa.String(80),sa.ForeignKey("farms.id",ondelete="SET NULL")),sa.Column("period_start",sa.DateTime(timezone=True),nullable=False),sa.Column("period_end",sa.DateTime(timezone=True),nullable=False),sa.Column("metrics_json",sa.JSON(),nullable=False),sa.Column("benchmark_json",sa.JSON(),nullable=False),sa.Column("forecast_json",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))


def downgrade():
    for table in ["atlas_analytics_snapshots","atlas_subscriptions","atlas_webhook_endpoints","atlas_api_credentials","atlas_workflow_instances","atlas_workflow_definitions","atlas_action_plan_items","atlas_consulting_visits","atlas_commercial_documents","atlas_business_parties"]:
        op.drop_table(table)
