"""precision hub sprints 71 80
Revision ID: 20260806_0031
Revises: 20260806_0030
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0031'; down_revision='20260806_0030'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('precision_device_adapters',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('adapter_key',sa.String(120),nullable=False),sa.Column('manufacturer',sa.String(180),nullable=False,server_default=''),sa.Column('protocol',sa.String(60),nullable=False,server_default='http-json'),sa.Column('configuration_json',sa.JSON(),nullable=False),sa.Column('secret_hash',sa.String(128),nullable=False,server_default=''),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('company_id','adapter_key',name='uq_precision_adapter_key'))
    op.create_table('animal_rfid_bindings',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('animal_id',sa.String(80),sa.ForeignKey('livestock_animals.id',ondelete='CASCADE'),nullable=False),sa.Column('tag_code',sa.String(180),nullable=False),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('bound_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('company_id','tag_code',name='uq_rfid_company_tag'))
    op.create_table('precision_events',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('device_id',sa.String(80),sa.ForeignKey('atlas_iot_devices_v2.id',ondelete='SET NULL')),sa.Column('animal_id',sa.String(80),sa.ForeignKey('livestock_animals.id',ondelete='SET NULL')),sa.Column('event_type',sa.String(80),nullable=False),sa.Column('severity',sa.String(20),nullable=False,server_default='info'),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('precision_geofences',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('polygon_json',sa.JSON(),nullable=False),sa.Column('rule_type',sa.String(30),nullable=False,server_default='inside'),sa.Column('active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('vision_human_reviews',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('analysis_id',sa.String(80),sa.ForeignKey('atlas_vision_analyses.id',ondelete='CASCADE'),nullable=False),sa.Column('reviewer_id',sa.String(80),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('decision',sa.String(30),nullable=False),sa.Column('corrected_result_json',sa.JSON(),nullable=False),sa.Column('notes',sa.Text(),nullable=False,server_default=''),sa.Column('reviewed_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('analysis_id',name='uq_vision_review_analysis'))
    op.create_table('remote_sensing_scenes',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('provider',sa.String(100),nullable=False,server_default='manual'),sa.Column('external_id',sa.String(180),nullable=False,server_default=''),sa.Column('captured_at',sa.DateTime(timezone=True),nullable=False),sa.Column('cloud_percent',sa.Float(),nullable=False,server_default='0'),sa.Column('indices_json',sa.JSON(),nullable=False),sa.Column('asset_uri',sa.String(700),nullable=False,server_default=''),sa.Column('status',sa.String(30),nullable=False,server_default='registered'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    for table,cols in [('animal_rfid_bindings',['company_id','farm_id','animal_id','tag_code']),('precision_device_adapters',['company_id','adapter_key']),('precision_events',['company_id','farm_id','event_type','severity','occurred_at']),('precision_geofences',['company_id','farm_id']),('vision_human_reviews',['company_id','analysis_id']),('remote_sensing_scenes',['company_id','farm_id','captured_at'])]:
        for col in cols: op.create_index(f'ix_{table}_{col}',table,[col])
def downgrade():
    for t in ['remote_sensing_scenes','vision_human_reviews','precision_geofences','precision_events','animal_rfid_bindings','precision_device_adapters']: op.drop_table(t)
