"""sprints 11 to 15

Revision ID: 20260806_0025
Revises: 20260806_0024
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0025'; down_revision='20260806_0024'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('atlas_brain_memories',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('area',sa.String(40),nullable=False),sa.Column('title',sa.String(180),nullable=False),sa.Column('summary',sa.Text(),nullable=False,server_default=''),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('decision_json',sa.JSON(),nullable=False),sa.Column('result_json',sa.JSON(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False,server_default='0'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_brain_plans',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('horizon',sa.String(30),nullable=False),sa.Column('title',sa.String(180),nullable=False),sa.Column('items_json',sa.JSON(),nullable=False),sa.Column('priority_score',sa.Float(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_vision_analyses',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('animal_id',sa.String(80),sa.ForeignKey('livestock_animals.id',ondelete='SET NULL'),nullable=True),sa.Column('analysis_type',sa.String(50),nullable=False),sa.Column('media_url',sa.String(600),nullable=False),sa.Column('input_json',sa.JSON(),nullable=False),sa.Column('result_json',sa.JSON(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('model_version',sa.String(80),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_iot_devices_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('device_type',sa.String(50),nullable=False),sa.Column('external_id',sa.String(180),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('configuration_json',sa.JSON(),nullable=False),sa.Column('last_seen_at',sa.DateTime(timezone=True),nullable=True),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_iot_telemetry_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('device_id',sa.String(80),sa.ForeignKey('atlas_iot_devices_v2.id',ondelete='CASCADE'),nullable=False),sa.Column('metric',sa.String(80),nullable=False),sa.Column('value',sa.Float(),nullable=False),sa.Column('unit',sa.String(30),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_cloud_jobs',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('job_type',sa.String(60),nullable=False),sa.Column('queue_name',sa.String(80),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('result_json',sa.JSON(),nullable=False),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('scheduled_at',sa.DateTime(timezone=True),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True),nullable=True),sa.Column('finished_at',sa.DateTime(timezone=True),nullable=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('atlas_web_workspaces',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('user_id',sa.String(80),sa.ForeignKey('users.id',ondelete='SET NULL'),nullable=True),sa.Column('portal_type',sa.String(40),nullable=False),sa.Column('layout_json',sa.JSON(),nullable=False),sa.Column('widgets_json',sa.JSON(),nullable=False),sa.Column('preferences_json',sa.JSON(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))

def downgrade():
    for t in ['atlas_web_workspaces','atlas_cloud_jobs','atlas_iot_telemetry_v2','atlas_iot_devices_v2','atlas_vision_analyses','atlas_brain_plans','atlas_brain_memories']: op.drop_table(t)
