"""ai operational and governance

Revision ID: 20260806_0030
Revises: 20260806_0029
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0030'
down_revision='20260806_0029'
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('ai_context_snapshots',
      sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('context_version',sa.String(40),nullable=False,server_default='1.0'),sa.Column('context_hash',sa.String(64),nullable=False),sa.Column('period_start',sa.DateTime(timezone=True)),sa.Column('period_end',sa.DateTime(timezone=True)),sa.Column('payload',sa.JSON(),nullable=False),sa.Column('quality',sa.JSON(),nullable=False),sa.Column('created_by',sa.String(80),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    for n,c in [('ix_ai_context_snapshots_tenant_id',['tenant_id']),('ix_ai_context_snapshots_company_id',['company_id']),('ix_ai_context_snapshots_farm_id',['farm_id']),('ix_ai_context_snapshots_context_hash',['context_hash']),('ix_ai_context_snapshots_created_at',['created_at'])]: op.create_index(n,'ai_context_snapshots',c)
    op.create_table('ai_recommendation_records',
      sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('context_snapshot_id',sa.String(80),sa.ForeignKey('ai_context_snapshots.id',ondelete='SET NULL')),sa.Column('area',sa.String(50),nullable=False),sa.Column('title',sa.String(220),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('algorithm',sa.String(100),nullable=False,server_default='atlas-rules'),sa.Column('model_version',sa.String(80),nullable=False,server_default='rules-v1'),sa.Column('evidence',sa.JSON(),nullable=False),sa.Column('limitations',sa.JSON(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False,server_default='0'),sa.Column('expected_impact',sa.JSON(),nullable=False),sa.Column('recommended_action',sa.Text(),nullable=False,server_default=''),sa.Column('priority',sa.String(30),nullable=False,server_default='medium'),sa.Column('human_decision',sa.String(30),nullable=False,server_default='pending'),sa.Column('observed_result',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('decided_at',sa.DateTime(timezone=True)))
    for n,c in [('ix_ai_recommendation_records_tenant_id',['tenant_id']),('ix_ai_recommendation_records_company_id',['company_id']),('ix_ai_recommendation_records_farm_id',['farm_id']),('ix_ai_recommendation_records_area',['area']),('ix_ai_recommendation_records_priority',['priority']),('ix_ai_recommendation_records_human_decision',['human_decision']),('ix_ai_recommendation_records_created_at',['created_at'])]: op.create_index(n,'ai_recommendation_records',c)
    op.create_table('ai_supervised_automations',
      sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE'),nullable=False),sa.Column('recommendation_id',sa.String(80),sa.ForeignKey('ai_recommendation_records.id',ondelete='SET NULL')),sa.Column('action_type',sa.String(60),nullable=False),sa.Column('payload',sa.JSON(),nullable=False),sa.Column('requires_approval',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('financial_limit',sa.Float(),nullable=False,server_default='0'),sa.Column('status',sa.String(30),nullable=False,server_default='pending_approval'),sa.Column('approved_by',sa.String(80),nullable=False,server_default=''),sa.Column('executed_by',sa.String(80),nullable=False,server_default=''),sa.Column('result',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('executed_at',sa.DateTime(timezone=True)))
    for n,c in [('ix_ai_supervised_automations_tenant_id',['tenant_id']),('ix_ai_supervised_automations_company_id',['company_id']),('ix_ai_supervised_automations_farm_id',['farm_id']),('ix_ai_supervised_automations_action_type',['action_type']),('ix_ai_supervised_automations_status',['status'])]: op.create_index(n,'ai_supervised_automations',c)
    op.create_table('ai_model_governance',
      sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('model_key',sa.String(120),nullable=False),sa.Column('version',sa.String(80),nullable=False),sa.Column('owner',sa.String(180),nullable=False),sa.Column('status',sa.String(30),nullable=False,server_default='draft'),sa.Column('authorized_data',sa.JSON(),nullable=False),sa.Column('minimum_metrics',sa.JSON(),nullable=False),sa.Column('current_metrics',sa.JSON(),nullable=False),sa.Column('drift_status',sa.String(30),nullable=False,server_default='unknown'),sa.Column('bias_status',sa.String(30),nullable=False,server_default='unknown'),sa.Column('rollback_version',sa.String(80),nullable=False,server_default=''),sa.Column('incident_notes',sa.Text(),nullable=False,server_default=''),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('company_id','model_key','version',name='uq_ai_model_governance_version'))
    for n,c in [('ix_ai_model_governance_tenant_id',['tenant_id']),('ix_ai_model_governance_company_id',['company_id']),('ix_ai_model_governance_model_key',['model_key']),('ix_ai_model_governance_status',['status'])]: op.create_index(n,'ai_model_governance',c)

def downgrade():
    op.drop_table('ai_model_governance'); op.drop_table('ai_supervised_automations'); op.drop_table('ai_recommendation_records'); op.drop_table('ai_context_snapshots')
