"""sprints 16 to 20

Revision ID: 20260806_0026
Revises: 20260806_0025
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0026'; down_revision='20260806_0025'; branch_labels=None; depends_on=None

def j(): return sa.JSON()
def dt(): return sa.DateTime(timezone=True)
def upgrade():
    op.create_table('atlas_billing_customers',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False,unique=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('provider',sa.String(40),nullable=False),sa.Column('provider_customer_id',sa.String(180),nullable=False),sa.Column('email',sa.String(320),nullable=False),sa.Column('tax_id',sa.String(40),nullable=False),sa.Column('metadata_json',j(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_billing_subscriptions_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('customer_id',sa.String(80),sa.ForeignKey('atlas_billing_customers.id',ondelete='SET NULL')),sa.Column('provider',sa.String(40),nullable=False),sa.Column('provider_subscription_id',sa.String(180),nullable=False),sa.Column('plan_code',sa.String(50),nullable=False),sa.Column('billing_cycle',sa.String(20),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('amount',sa.Float(),nullable=False),sa.Column('currency',sa.String(10),nullable=False),sa.Column('current_period_start',dt()),sa.Column('current_period_end',dt()),sa.Column('cancel_at_period_end',sa.Boolean(),nullable=False),sa.Column('metadata_json',j(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_billing_events',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('provider',sa.String(40),nullable=False),sa.Column('event_type',sa.String(80),nullable=False),sa.Column('external_id',sa.String(180),nullable=False),sa.Column('payload_json',j(),nullable=False),sa.Column('processed',sa.Boolean(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_public_api_apps',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('client_id',sa.String(120),nullable=False,unique=True),sa.Column('client_secret_hash',sa.String(255),nullable=False),sa.Column('scopes_json',j(),nullable=False),sa.Column('rate_limit_per_minute',sa.Integer(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_public_api_events',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('event_name',sa.String(120),nullable=False),sa.Column('resource_type',sa.String(80),nullable=False),sa.Column('resource_id',sa.String(80),nullable=False),sa.Column('payload_json',j(),nullable=False),sa.Column('occurred_at',dt(),nullable=False))
    op.create_table('atlas_analytics_datasets_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('grain',sa.String(60),nullable=False),sa.Column('dimensions_json',j(),nullable=False),sa.Column('measures_json',j(),nullable=False),sa.Column('retention_days',sa.Integer(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_analytics_facts_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('dataset_id',sa.String(80),sa.ForeignKey('atlas_analytics_datasets_v2.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='SET NULL')),sa.Column('period_start',dt(),nullable=False),sa.Column('period_end',dt(),nullable=False),sa.Column('dimensions_json',j(),nullable=False),sa.Column('measures_json',j(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_ml_model_registry_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('task_type',sa.String(80),nullable=False),sa.Column('version',sa.String(50),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('artifact_uri',sa.String(600),nullable=False),sa.Column('feature_schema_json',j(),nullable=False),sa.Column('metrics_json',j(),nullable=False),sa.Column('training_data_json',j(),nullable=False),sa.Column('approved_at',dt()),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_ml_predictions_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('model_id',sa.String(80),sa.ForeignKey('atlas_ml_model_registry_v2.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='SET NULL')),sa.Column('animal_id',sa.String(80),sa.ForeignKey('livestock_animals.id',ondelete='SET NULL')),sa.Column('input_json',j(),nullable=False),sa.Column('output_json',j(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('explanation_json',j(),nullable=False),sa.Column('created_at',dt(),nullable=False))
    op.create_table('atlas_enterprise_releases',sa.Column('id',sa.String(80),primary_key=True),sa.Column('version',sa.String(50),nullable=False,unique=True),sa.Column('channel',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('checklist_json',j(),nullable=False),sa.Column('artifacts_json',j(),nullable=False),sa.Column('notes',sa.Text(),nullable=False),sa.Column('created_at',dt(),nullable=False))

def downgrade():
    for t in ['atlas_enterprise_releases','atlas_ml_predictions_v2','atlas_ml_model_registry_v2','atlas_analytics_facts_v2','atlas_analytics_datasets_v2','atlas_public_api_events','atlas_public_api_apps','atlas_billing_events','atlas_billing_subscriptions_v2','atlas_billing_customers']: op.drop_table(t)
