"""data platform sprints 101-110
Revision ID: 20260806_0034
Revises: 20260806_0033
"""
from alembic import op
import sqlalchemy as sa
revision='20260806_0034'; down_revision='20260806_0033'; branch_labels=None; depends_on=None
TABLES=['domain_event_outbox','dead_letter_events','warehouse_dimensions','warehouse_facts','kpi_definitions','kpi_observations','benchmark_cohorts','benchmark_snapshots','report_definitions_v2','realtime_metrics','distributed_cache_entries','background_jobs']
def upgrade():
    op.create_table('domain_event_outbox',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('event_type',sa.String(160),nullable=False),sa.Column('aggregate_type',sa.String(100),nullable=False),sa.Column('aggregate_id',sa.String(100),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('idempotency_key',sa.String(180),nullable=False,unique=True),sa.Column('status',sa.String(30),nullable=False),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.Column('published_at',sa.DateTime(timezone=True)),sa.Column('last_error',sa.Text(),nullable=False))
    op.create_table('dead_letter_events',sa.Column('id',sa.String(80),primary_key=True),sa.Column('event_id',sa.String(80),nullable=False),sa.Column('event_type',sa.String(160),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('error',sa.Text(),nullable=False),sa.Column('failed_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('warehouse_dimensions',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('dimension_type',sa.String(80),nullable=False),sa.Column('natural_key',sa.String(160),nullable=False),sa.Column('attributes_json',sa.JSON(),nullable=False),sa.Column('valid_from',sa.DateTime(timezone=True),nullable=False),sa.Column('valid_to',sa.DateTime(timezone=True)),sa.UniqueConstraint('company_id','dimension_type','natural_key',name='uq_warehouse_dimension'))
    op.create_table('warehouse_facts',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('fact_type',sa.String(100),nullable=False),sa.Column('dimensions_json',sa.JSON(),nullable=False),sa.Column('measures_json',sa.JSON(),nullable=False),sa.Column('source_event_id',sa.String(80)),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('kpi_definitions',sa.Column('id',sa.String(80),primary_key=True),sa.Column('code',sa.String(100),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('domain',sa.String(80),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('formula',sa.Text(),nullable=False),sa.Column('source_json',sa.JSON(),nullable=False),sa.Column('periodicity',sa.String(30),nullable=False),sa.Column('owner',sa.String(160),nullable=False),sa.Column('minimum_quality',sa.Float(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False),sa.UniqueConstraint('code','version',name='uq_kpi_code_version'))
    op.create_table('kpi_observations',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('farm_id',sa.String(80),sa.ForeignKey('farms.id',ondelete='CASCADE')),sa.Column('kpi_code',sa.String(100),nullable=False),sa.Column('value',sa.Float(),nullable=False),sa.Column('period_start',sa.DateTime(timezone=True),nullable=False),sa.Column('period_end',sa.DateTime(timezone=True),nullable=False),sa.Column('quality_score',sa.Float(),nullable=False),sa.Column('dimensions_json',sa.JSON(),nullable=False))
    op.create_table('benchmark_cohorts',sa.Column('id',sa.String(80),primary_key=True),sa.Column('code',sa.String(100),nullable=False,unique=True),sa.Column('description',sa.Text(),nullable=False),sa.Column('filters_json',sa.JSON(),nullable=False),sa.Column('minimum_sample_size',sa.Integer(),nullable=False),sa.Column('active',sa.Boolean(),nullable=False))
    op.create_table('benchmark_snapshots',sa.Column('id',sa.String(80),primary_key=True),sa.Column('cohort_id',sa.String(80),sa.ForeignKey('benchmark_cohorts.id',ondelete='CASCADE'),nullable=False),sa.Column('kpi_code',sa.String(100),nullable=False),sa.Column('period_end',sa.DateTime(timezone=True),nullable=False),sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('percentiles_json',sa.JSON(),nullable=False),sa.Column('generated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('report_definitions_v2',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('metrics_json',sa.JSON(),nullable=False),sa.Column('filters_json',sa.JSON(),nullable=False),sa.Column('groupings_json',sa.JSON(),nullable=False),sa.Column('visualization_json',sa.JSON(),nullable=False),sa.Column('schedule',sa.String(80),nullable=False),sa.Column('active',sa.Boolean(),nullable=False))
    op.create_table('realtime_metrics',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('metric_key',sa.String(120),nullable=False),sa.Column('scope_key',sa.String(180),nullable=False),sa.Column('value',sa.Float(),nullable=False),sa.Column('version',sa.Integer(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('company_id','metric_key','scope_key',name='uq_realtime_metric_scope'))
    op.create_table('distributed_cache_entries',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('cache_key',sa.String(240),nullable=False),sa.Column('value_json',sa.JSON(),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('background_jobs',sa.Column('id',sa.String(80),primary_key=True),sa.Column('tenant_id',sa.String(80),nullable=False),sa.Column('company_id',sa.String(80),sa.ForeignKey('companies.id',ondelete='CASCADE'),nullable=False),sa.Column('job_type',sa.String(120),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('attempts',sa.Integer(),nullable=False),sa.Column('max_attempts',sa.Integer(),nullable=False),sa.Column('available_at',sa.DateTime(timezone=True),nullable=False),sa.Column('locked_at',sa.DateTime(timezone=True)),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('last_error',sa.Text(),nullable=False))
def downgrade():
    for table in reversed(TABLES): op.drop_table(table)
